# Generated by Django 4.0.3 on 2022-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='alialiali@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
